name: CD

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      mm: ${{ steps.vars.outputs.mm }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: vars
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          MAJOR_MINOR=$(echo "$TAG" | cut -d. -f1-2)
          echo "mm=$MAJOR_MINOR" >> $GITHUB_OUTPUT

      - name: Build and push image to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository }}
          docker build -t $IMAGE:${{ steps.vars.outputs.tag }} -t $IMAGE:${{ steps.vars.outputs.mm }} -t $IMAGE:latest .
          docker push $IMAGE:${{ steps.vars.outputs.tag }}
          docker push $IMAGE:${{ steps.vars.outputs.mm }}
          docker push $IMAGE:latest

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          generate_release_notes: true

  deploy-dev:
    needs: release
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Push image to Artifact Registry (GAR)
        run: |
          SRC_IMAGE="ghcr.io/${{ github.repository }}:${{ needs.release.outputs.tag }}"
          GAR_HOST="${{ secrets.GCP_REGION }}-docker.pkg.dev"
          GAR_REPO="${GAR_HOST}/${{ secrets.GCP_PROJECT_ID }}/solaroptima-ml/solaroptima-ml"
          GAR_IMAGE="${GAR_REPO}:${{ needs.release.outputs.tag }}"
          echo "Pulling $SRC_IMAGE"
          docker pull "$SRC_IMAGE"
          echo "Tagging and pushing to $GAR_IMAGE"
          docker tag "$SRC_IMAGE" "$GAR_IMAGE"
          gcloud auth configure-docker "$GAR_HOST" -q
          docker push "$GAR_IMAGE"

      - name: Deploy to Cloud Run (dev)
        run: |
          GAR_HOST="${{ secrets.GCP_REGION }}-docker.pkg.dev"
          GAR_IMAGE="${GAR_HOST}/${{ secrets.GCP_PROJECT_ID }}/solaroptima-ml/solaroptima-ml:${{ needs.release.outputs.tag }}"
          gcloud run deploy solaroptima-ml-dev \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --region="${{ secrets.GCP_REGION }}" \
            --image="$GAR_IMAGE" \
            --platform=managed \
            --allow-unauthenticated \
            --gpu=type=nvidia-tesla-t4,count=1 \
            --add-volume name=models,type=cloud-storage,bucket=${{ secrets.GCS_MODELS_BUCKET }} \
            --add-volume-mount volume=models,mount-path=/models,read-only \
            --min-instances=0 \
            --max-instances=3 \
            --set-env-vars LOG_LEVEL=${{ secrets.LOG_LEVEL || 'INFO' }},DSM_CACHE_ENABLED=${{ secrets.DSM_CACHE_ENABLED || 'true' }},USE_PLACEHOLDER_PVGIS=${{ secrets.USE_PLACEHOLDER_PVGIS || 'true' }},USE_PLACEHOLDER_BEIS=${{ secrets.USE_PLACEHOLDER_BEIS || 'true' }}

  deploy-staging:
    needs: [release, deploy-dev]
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run (staging)
        run: |
          GAR_HOST="${{ secrets.GCP_REGION }}-docker.pkg.dev"
          GAR_IMAGE="${GAR_HOST}/${{ secrets.GCP_PROJECT_ID }}/solaroptima-ml/solaroptima-ml:${{ needs.release.outputs.tag }}"
          gcloud run deploy solaroptima-ml-staging \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --region="${{ secrets.GCP_REGION }}" \
            --image="$GAR_IMAGE" \
            --platform=managed \
            --allow-unauthenticated \
            --gpu=type=nvidia-tesla-t4,count=1 \
            --add-volume name=models,type=cloud-storage,bucket=${{ secrets.GCS_MODELS_BUCKET }} \
            --add-volume-mount volume=models,mount-path=/models,read-only \
            --min-instances=0 \
            --max-instances=3 \
            --set-env-vars LOG_LEVEL=${{ secrets.LOG_LEVEL || 'INFO' }},DSM_CACHE_ENABLED=${{ secrets.DSM_CACHE_ENABLED || 'true' }},USE_PLACEHOLDER_PVGIS=${{ secrets.USE_PLACEHOLDER_PVGIS || 'true' }},USE_PLACEHOLDER_BEIS=${{ secrets.USE_PLACEHOLDER_BEIS || 'true' }}

  deploy-prod:
    needs: [release, deploy-staging]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run (prod)
        run: |
          GAR_HOST="${{ secrets.GCP_REGION }}-docker.pkg.dev"
          GAR_IMAGE="${GAR_HOST}/${{ secrets.GCP_PROJECT_ID }}/solaroptima-ml/solaroptima-ml:${{ needs.release.outputs.tag }}"
          gcloud run deploy solaroptima-ml-prod \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --region="${{ secrets.GCP_REGION }}" \
            --image="$GAR_IMAGE" \
            --platform=managed \
            --allow-unauthenticated \
            --gpu=type=nvidia-tesla-t4,count=1 \
            --add-volume name=models,type=cloud-storage,bucket=${{ secrets.GCS_MODELS_BUCKET }} \
            --add-volume-mount volume=models,mount-path=/models,read-only \
            --min-instances=0 \
            --max-instances=3 \
            --set-env-vars LOG_LEVEL=${{ secrets.LOG_LEVEL || 'INFO' }},DSM_CACHE_ENABLED=${{ secrets.DSM_CACHE_ENABLED || 'true' }},USE_PLACEHOLDER_PVGIS=${{ secrets.USE_PLACEHOLDER_PVGIS || 'true' }},USE_PLACEHOLDER_BEIS=${{ secrets.USE_PLACEHOLDER_BEIS || 'true' }}